=== evstratovavalya055-afk/lab-web/lab4/timetable_external.dtd
<!ELEMENT timetable (day*)>
<!ELEMENT day (lesson+)>
<!ELEMENT lesson (timeFrom, timeTo, subject, teacher, room?)>
<!ELEMENT timeFrom (#PCDATA)>
<!ELEMENT timeTo (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT teacher (#PCDATA)>
<!ELEMENT room (#PCDATA)>
<!ATTLIST day
    dayOfWeek CDATA #REQUIRED>
<!ATTLIST lesson
    type CDATA #REQUIRED>

=== evstratovavalya055-afk/lab-web/lab4/timetable_with_external_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timetable SYSTEM "timetable_external.dtd">
<timetable>
  <day dayOfWeek="Monday">
    <lesson type="practical">
      <timeFrom>08.00</timeFrom>
      <timeTo>09.30</timeTo>
      <subject>Deutsch</subject>
      <teacher>Borisova</teacher>
      <room>216</room>
    </lesson>
    <lesson type="lecture">
      <timeFrom>09.40</timeFrom>
      <timeTo>11.10</timeTo>
      <subject>SAP Administration</subject>
      <teacher>Egorov</teacher>
      <room>384</room>
    </lesson>
    <lesson type="practical">
      <timeFrom>11.20</timeFrom>
      <timeTo>12.50</timeTo>
      <subject>SAP Administration</subject>
      <teacher>Petrov</teacher>
      <room>384</room>
    </lesson>
  </day>
</timetable>
